FROM mhart/alpine-node:base-7.7

ADD https://yarnpkg.com/latest.tar.gz /opt/yarn.tar.gz
RUN yarnDirectory=/opt/yarn && \
    mkdir -p "$yarnDirectory" && \
    tar -xzf /opt/yarn.tar.gz -C "$yarnDirectory" && \
    ln -s "$yarnDirectory/dist/bin/yarn" /usr/local/bin/ && \
    rm /opt/yarn.tar.gz

ADD package.json yarn.lock /tmp/

ADD .yarn-cache.tgz /

RUN mkdir -p /opt/source-app && \
    cd /tmp && yarn install --modules-folder /opt/source-app/node_modules/

ADD . /opt/source-app

RUN cd /opt/source-app && yarn run build

RUN mkdir -p /opt/app && \
    cp -r /opt/source-app/server /opt/app && \
    cp -r /opt/source-app/public /opt/app

RUN cd /tmp && yarn install --prod --modules-folder /opt/app/node_modules/
